#server:
#  port: 8443
#  ssl:
#    enabled: true
#    key-alias: spring-security
#    key-store: keystore.p12
#    key-store-type: PKCS12
#    key-store-password: spring-security
#    key-password: spring-security

## Security
security:
  user:
    name: springboot
    password: workshop
## add content ----
#  oauth2:
#    client:
#      client-id: myid
#      client-secret: mysecret
# add content ^^^^

#security:
#  oauth2:
#    client:
#      clientId: 89630a412fa314777dc2
#      clientSecret: c7a29ec26ec7805e78b496ea67cc13e5a9b8bcf0
#      accessTokenUri: https://github.com/login/oauth/access_token
#      userAuthorizationUri: https://github.com/login/oauth/authorize
#      clientAuthenticationScheme: form
#    resource:
#      userInfoUri: https://api.github.com/user
#      preferTokenInfo: false